server:
  port: 10934

spring:
  datasource:
    url: jdbc:mysql://home-nuc:3306/web_app?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin@123_KOFEE
    driver-class-name: com.mysql.cj.jdbc.Driver